server:
  port: 8080


---
spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8085
---
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order
          destination: FinalProject
          contentType: application/json
        event-out:
          destination: FinalProject
          contentType: application/json
logging:
  level:
    root: ${ORDER_LOG_LEVEL}
    org:
      hibernate:
        SQL: ${ORDER_LOG_LEVEL}
      springframework:
        cloud: ${ORDER_LOG_LEVEL}